name: Build and Test with Gradle

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        os: [ ubuntu-latest, windows-latest, macos-latest ]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Run Tests
        uses: make test
